# Generated by Django 3.1.7 on 2021-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='enddate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания действия записи'),
        ),
    ]
